import { StyleSheet } from "react-native";
import theme from "../../theme/GlobalTheme";
import { heightPercentageToDP as hp, widthPercentageToDP as wp } from "react-native-responsive-screen";

const styles = StyleSheet.create({
    container:{
        flex:1,
        width:'100%',
        alignItems:'center',
        backgroundColor:theme.colors.white,
    }, 
    heading:{
           width:wp('100%'),
           fontSize:22,
           fontFamily:'Raleway-SemiBold',
           color:theme.colors.black,
           marginTop:hp('5%')
    },
    subHeading:{
        width:wp(75),
        fontSize:10,
        fontFamily:'Raleway-SemiBold',
        color:theme.colors.black,
        paddingTop:'2%'
    },
    headingContainer:{
        width:wp('90%')
    },
    weekContainer:{
        alignItems:'center',
        justifyContent:'center',
        padding:hp(1),
        paddingLeft:hp(2),
        paddingRight:hp(2),
        borderRadius:4,
        marginLeft:hp('1%')
    },
    week:{
        fontSize:10,
        fontFamily:'Raleway-Regular',
    },
    container2:{
        flexDirection:'row',
        width:wp('100%'),
        alignItems:'center',
        paddingLeft:hp('2%'),
        paddingRight:hp('1%'),
        marginTop:hp('2%'),
        height:hp(6),
        justifyContent:'space-between'
    },
    behaviorContainer:{
        flexDirection:'row',
        width:'90%',
        justifyContent:'space-between',
        alignItems:'center',
        height:hp(18),
        borderWidth:1,
        marginTop:'5%',
        paddingTop:'2%',
        paddingBottom:'0%',
        padding:'5%',
        borderRadius:8,
        borderColor:theme.colors.lightgrey,
    },
    day1Image:{
        height:hp(12),
        width:wp(24),
        marginBottom:'5%'
    },
    dayText:{
        fontSize:8,
        fontFamily:'Raleway-Bold',
        // backgroundColor:theme.colors.lightgrey,
        color:theme.colors.grey,
        justifyContent:'center',
        alignItems:'center',
        textAlign:'center',
        textAlignVertical:'center',
        padding:2,
        paddingLeft:5,
        paddingRight:5,
        borderRadius:2
    },
    dayContainer:{
        flexDirection:'column',
        height:'100%',
        paddingTop:'4%',
    },
    behaviorText:{
        fontSize:8,
        fontFamily:'Raleway-Semibold',
        color:theme.colors.grey,
        textAlign:'center',
        alignItems:'center',
        textAlignVertical:'center',
        paddingLeft:'5%',
    },
    restText:{
        fontSize:10,
        fontFamily:'Raleway-SemiBold',
        color:theme.colors.black,
        paddingTop:'4%',
        width:150
    },
    continueContainer:{
        alignItems:'center',
        justifyContent:'center',
        height:24,
        borderRadius:2,
        width:64,
        backgroundColor:theme.colors.darkBlue,
        marginTop:'15%'
    },
    continue:{
        color:theme.colors.darkBlue,
        fontSize:10,
        fontFamily:'Raleway-Medium',
        marginTop:'15%'
    },
    dot:{
        height:13,
        width:13,
        borderRadius:10,
        backgroundColor:theme.colors.yellow,
        alignItems:'center',
        justifyContent:'center',
        marginLeft:'8%',
        paddingTop:'4%'
        },
        tick:{
            height:10,
            width:12,
        },
        day2Image:{
            width:wp(20),
            height:hp(12)
        },
        day3Image:{
            width:wp(18),
            height:hp(12)
        }
})
export default styles;