import { StyleSheet } from "react-native";
import theme from "../../theme/GlobalTheme";

const styles = StyleSheet.create({
    container:{
        flex:1,
        width:'100%',
        alignItems:'center',
        backgroundColor:theme.colors.white,
    },
    heading:{
        width:'90%',
        marginTop:'10%',
        fontSize:22,
        fontFamily:'Raleway-SemiBold',
        color:theme.colors.black,
    },
    subHeading:{
        fontSize:8,
        fontFamily:'Raleway-Medium',
        width:'90%',
        color:theme.colors.black,
        paddingTop:'1%'
    },
    daysContainer:{
        flexDirection:'row',
        alignItems:'center',
        width:'100%',
        paddingTop:'5%'
    },
    dayBlock:{
        height:52,
        width:38,
        borderWidth:1,
        borderRadius:6,
        alignItems:'center',
        justifyContent:'space-evenly',
        marginLeft:5,
        padding:5
    },
    day:{
        fontSize:10,
        fontFamily:'Raleway-Medium',
        color:theme.colors.black,
    },
    dayNo:{
        fontSize:8,
        fontFamily:'Raleway-Regular',
        color:theme.colors.black,
        paddingBottom:2
    },
    circle:{
        height:12,
        width:12
    },
    flatlist:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        paddingLeft:'4%'
    },
    addActivity:{
        height:60,
        width:'90%',
        alignItems:'center',
        justifyContent:'center',
        borderWidth:1,
        borderRadius:6,
        borderColor:theme.colors.lightgrey,
        marginTop:'10%'
    },
    addActivityText:{
        fontSize:12,
        fontFamily:'Raleway-Bold',
        color:theme.colors.black,
    }
})
export default styles;