import { StyleSheet } from "react-native";
import theme from "../../theme/GlobalTheme";
import { heightPercentageToDP as hp, widthPercentageToDP as wp } from "react-native-responsive-screen";

const styles = StyleSheet.create({
    container:{
        // flex:1,
        width:'100%',
        alignItems:'center',
        backgroundColor:theme.colors.white,
    },
    back:{
        height:26,
        width:26,
    }, 
    backContainer:{
        marginTop:'10%',
        width:'90%'
    },
    heading:{
        fontSize:20,
        fontFamily:'Raleway-Bold',
        color: theme.colors.yellow,
        width:'80%',
        padding:'1%'
    },
    text:{
        fontSize:12,
        fontFamily:'Raleway-SemiBold',
        color:theme.colors.black,
        width:'90%',
        padding:'1%'
    },
    textContainer:{
        width:'90%',
        marginTop:'5%'
    },
    itemContainer:{
        width:'90%',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'row',
        marginTop:'8%'
    },
    imageContainer:{
        height:hp(18),
        width:hp(13),
    },
    image:{
        height:'100%',
        width:'100%'
    },
    remindContainer:{
        width:'90%',
        justifyContent:'space-between',
        flexDirection:'row',
        alignItems:'center',
        marginTop:'7%'
    },
    remindText:{
        color:theme.colors.yellow,
        fontSize:14,
        fontFamily:'Raleway-Bold'
    },
    time:{
        color:theme.colors.black,
        fontSize:14,
        fontFamily:'Lalezar-Regular',
        borderWidth:1,
        borderColor:theme.colors.yellow,
        paddingLeft:'4%',
        paddingRight:'4%',
        textAlign:'center',
        borderRadius:6,
        textAlignVertical:'center',
        padding:'1%'
    },
    bottomContainer:{
        width:wp('100%'),
        flex:1,
        alignItems:'center',
        justifyContent:'flex-end',
        marginBottom:hp('10%'),
        marginTop:hp('17%'),
    },
    bottomText:{
        fontSize:14,
        fontFamily:'Raleway-SemiBold',
        color:theme.colors.black,
        textAlign:'center',
        textAlignVertical:'center',
        height:30,
    },
    bottomTextContainer:{
        borderWidth:1,
        borderColor:theme.colors.yellow,
        height:42,
        padding:'3%',
        borderRadius:6,
        alignItems:'center',
        justifyContent:'center',
        marginBottom:'5%'
    }
})
export default styles;