import { StyleSheet } from "react-native";
import theme from "../../theme/GlobalTheme";

const styles = StyleSheet.create({
    container:{
        flex:1,
        width:'100%',
        alignItems:'center',
        backgroundColor:theme.colors.white,
        paddingBottom:'5%'
    },
    heading:{
        width:'90%',
        color:theme.colors.black,
        fontSize:22,
        fontFamily:'Raleway-SemiBold',
        paddingTop:'10%'
    },
    buttonContainer:{
        height:26,
        width:63,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:theme.colors.darkBlue,
        borderRadius:4
    },
    buttonText:{
        color:theme.colors.white,
        fontSize:10,
        fontFamily:'Raleway-SemiBold'
    },
    date:{
        fontSize:12,
        fontFamily:'Raleway-SemiBold',
        color:theme.colors.black,
        width:'90%',
        marginTop:'5%'
    },
    happyBack:{
        height:44,
        width:42,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:8,
    },
    happy:{
        height:24,
        width:24
    },
    itemContainer:{
        width:'90%',
        marginTop:'2%',
        borderWidth:1,
        padding:'2%',
        borderRadius:6,
        borderColor:theme.colors.lightgrey
    },
    imageContainer:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center'
    },
    headingContainer:{
        width:'70%',
    },
    heading1:{
        fontSize:10,
        fontFamily:'Raleway-SemiBold',
        color:theme.colors.black,
    }, 
    time:{
        fontSize:8,
        fontFamily:'Raleway-SemiBold',
        color:theme.colors.grey
    },
    dots:{
        height:4,
        width:15,
        marginRight:'5%'
    },
    text:{
        fontSize:12,
        fontFamily:'Raleway-Medium',
        color:theme.colors.black,
        width:260,
        paddingTop:5
    },
    bottomContainer:{
        flexDirection:'row',
        justifyContent:'flex-start',
        width:'90%',
        marginTop:'3%'
    },
    firstText:{
        fontSize:7,
        fontFamily:'Raleway-Medium',
        backgroundColor:'rgba(243, 244, 246, 0.8)',
        padding:'1%',
        paddingLeft:'2%',
        paddingRight:'2%',
        textAlign:'center',
        textAlignVertical:'center',
        borderRadius:2,
        marginLeft:'2%'
    }, 
    dotsBack:{
        height:13,
        width:25, 
        backgroundColor:'rgba(243, 244, 246, 0.8)',
    }
})
export default styles;